<a href="https://colab.research.google.com/github/ocean5apphotmail/deep-learning-from-scratch/blob/master/neuralNetwork_from_scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 手撸神经网络

In [9]:
import numpy
import scipy.special # sigmoid function expit()


In [32]:
# neural network class definition

class neuralNetwork :
  # initialise the neural network
  def __init__( self, inputnodes, hiddennodes, outputnodes, learningrate) :
    # set number of nodes in each input, hidden, output layer
    self.inodes = inputnodes
    self.hnodes = hiddennodes
    self.onodes = outputnodes

    # learningrate
    self.lr = learningrate

    # weights inside the arrays are w i j, where link is from node i to node j in the next layer
    # w11 w21 etc 
    # self.wih = (numpy.random.rand(self.hnodes, self.inodes) - 0.5) # input-hidden 连接矩阵 
    # self.wio = (numpy.random.rand(self.onodes, self.hnodes) - 0.5) # hidden-output 连接矩阵
    # Example: input 5nodes, hidden 3nodes, output 4nodes
    # answer： X = WI ,X 是hidden输入 I是input, W是input-hidden 连接矩阵 
    #     I是 5行1列，X是3行1列,所以W是3行5列

    # 也可以使用正态分布权重 平均值为0， 标准方差为节点传入连接数目的开方
    self.wih = numpy.random.normal(0.0, pow(self.hnodes, -0.5), (self.hnodes, self.inodes)) # 正态分布中心设为0.0，标准方差 pow(self.hnodes, -0.5),
    self.who = numpy.random.normal(0.0, pow(self.onodes, -0.5), (self.onodes, self.hnodes)) # 最后一个参数是numpy数组形状大小

    # 激活函数 Sigmoid (activation function)
    self.activation_function = lambda x: scipy.special.expit(x)

    pass

  # train the neural network
  def train(self, inputs_list, targets_list) :

    inputs = numpy.array(inputs_list, ndmin = 2).T 
    targets = numpy.array(targets_list, ndmin = 2).T 
    
    # 正向传播
    hidden_inputs = numpy.dot(self.wih, inputs)
    hidden_outputs = self.activation_function(hidden_inputs)
    final_inputs = numpy.dot(self.who, hidden_outputs)
    final_outputs = self.activation_function(final_inputs)
    
    # 计算误差
    output_errors = targets - final_outputs

    # 反向传播
    # errors(hidden) = W(hidden-output)(T) * errors(output)
    hidden_errors = numpy.dot(self.who.T, output_errors)
    # 更新权重 hidden-output layers
    self.who += self.lr * numpy.dot((output_errors * final_outputs * (1.0 - final_outputs)), numpy.transpose(hidden_outputs))
    # 更新权重 input-hidden layers
    self.wih += self.lr * numpy.dot((hidden_errors * hidden_outputs * (1.0 - hidden_outputs)), numpy.transpose(inputs))

    pass

  # query the neural network
  def query(self, inputs_list) :
    # convert inputs list to 2d array
    #print('input_list:' + str(inputs_list))
    inputs = numpy.array(inputs_list, ndmin = 2).T # 这是干啥的？
    #inputs2 = numpy.array(inputs_list, ndmin = 2)
    #print('inputs:' + str(inputs))
    #print('inputs2:' + str(inputs2))
    # X(hidden) = W(input-hidden) * I
    hidden_inputs = numpy.dot(self.wih, inputs)
    # O(hidden) = Sigmoid(X(hidden))
    hidden_outputs = self.activation_function(hidden_inputs)
    # 
    final_inputs = numpy.dot(self.who, hidden_outputs)
    #
    final_outputs = self.activation_function(final_inputs)
    
    return final_outputs


# 新段落

In [33]:
# number of input, hidden, output nodes
inputnodes = 3
hiddennodes = 3
outputnodes = 3
# learningrate is 0.5
learning_rate = 0.5

# create instaance of neural network
n = neuralNetwork(inputnodes, hiddennodes, outputnodes, learning_rate)

In [34]:
numpy.random.rand(3,3)

array([[0.51058562, 0.41922841, 0.91831977],
       [0.74865872, 0.63088442, 0.93204991],
       [0.19462066, 0.60346104, 0.55145025]])

In [35]:
numpy.random.rand(3,3) - 0.5 # -0.5到0.5的随机值矩阵

array([[ 0.23171816,  0.11961114, -0.26058272],
       [-0.28230843, -0.35241489, -0.27438696],
       [ 0.48776803,  0.0707728 ,  0.28899781]])

In [36]:
n.query([1.0,0.5,-0.9])

array([[0.53077511],
       [0.41243739],
       [0.75823633]])